### ISSUE TITLE
Selection almost invisible with Code->Identifier under caret

### ISSUE THREAD

**Issue by olfway** [hardhackerlabs/theme-jetbrains#3]
<img width="304" alt="image" src="https://github.com/hardhackerlabs/theme-jetbrains/assets/32193/9a719a07-178e-42fc-a7ad-78185570e549">

Here "enable" is selected, and "enable_helm" is highlighted by "Identifier under caret"

**Comment by anson0370** [comment]
我会看看怎么优化这个显示效果

**Comment by anson0370** [comment]
Sorry for accidentally closing the issue. I'll look into how to optimize this problem.

**Comment by anson0370** [comment]
I just uploaded version 0.2.5 which has improvements for this issue. Please update after it has been approved.

**Comment by olfway** [comment]
<img width="217" alt="image" src="https://github.com/hardhackerlabs/theme-jetbrains/assets/32193/b4c6843a-9c6a-4d17-bd5f-5e9f8a82cf52">

Now it's much better, thanks!
